### PR TITLE
Fix keybinding table layout

### PR DESCRIPTION
**Pull request by purcell**
GFM didn't seem to be rendering the modified table properly, so I felt obliged to fix it since I'd badgered you into changing things. :-)

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
:+1: :)

**Comment by bbatsov** [comment]
Hmm. Does the problem still exist? The table looks fine to me.

**Comment by purcell** [comment]
Looks okay to me too, now. Will close this.

**Comment by purcell** [comment]
(Think I remember reading about github switching to kramdown, or maybe that was just for the new jekyll version... in any case, they may have fixed it on their side.)

**Pull request closed without merging**
