### PR TITLE
Add ability to kill dired buffers

### PR DESCRIPTION
**Pull request by azzamsa**
Kill all buffer but current one and special buffers.
Ignore buffers that start with "*" and white space.

### CODE REVIEW

**Comment by azzamsa** [comment]
But for me my self. I use this approach. I don't know if it would make sense to add to crux.

```elisp
(require 'cl-lib)

;;;###autoload
(defun aza-kill-other-buffers ()
  "Kill all buffers but current buffer and special buffers.
(Buffer that start with '*' and white space ignored)"
  (interactive)
  (let ((killed-bufs 0))
    (dolist (buffer (delq (current-buffer) (buffer-list)))
      (let ((name (buffer-name buffer)))
        (when (and name (not (string-equal name ""))
                   (/= (aref name 0) ?\s)
                   (string-match "^[^\*]" name))
          (cl-incf killed-bufs)
          (funcall 'kill-buffer buffer))))
    (message "Killed %d buffer(s)" killed-bufs)))
```

**Comment by bbatsov** [comment]
So, the point is that we forgot the filter out the special buffers, right? 

Your functions seems pretty similar unless I'm missing something.

**Comment by azzamsa** [comment]
> So, the point is that we forgot the filter out the special buffers, right?

No. You've already done that using `#'buffer-file-name`. It will take visiting buffer only. 

But it doesn't kill dired-buffer (because filtered by `#'buffer-file-name`). So I use another approach. Take all buffer, filter; the current one, the one that start with '*' and white space. then delete the rest.

**Comment by azzamsa** [comment]
Fix for https://github.com/bbatsov/crux/issues/49

**Comment by bbatsov** [comment]
Hmm, I'm confused now - dired buffers are not visiting files and `buffer-file-name` returns nil for them, so it seems to me that should be killed as they are supposed to. Am I missing something?

**Comment by azzamsa** [comment]
> so it seems to me that should be killed as they are supposed to

But using old crux `kill-other-buffer`. the dired-buffers dosn't get killed.

To reproduce:

1) open some file (e.g foo.md, baz.org)
2) open some dired dir (foo-dir, baz-dir)
3) call `crux-kill-other-buffer`
4) foo.md and baz.org get killed but not foo-dir and baz-dir

We want foo-dir and baz-dir get killled too.

**Comment by azzamsa** [comment]
@bbatsov Maybe you want to re-consider. I will give screenshot of each step. Hope there is no more misunderstanding.

1) open some file and some directory/dired

Now we have:
- projecst - Dired
- inbox.org - file
- trackers - Dired
- main.py - file



2) we call `crux-kill-other-buffers`. Our current file is main.py

Crux only remove:
- projecst - Dired - **not killed**
- inbox.org - file
- trackers - Dired - **not killed**
- main.py - file - current-file

I and some other people https://github.com/bbatsov/crux/issues/49 like to kill all of the **not killed** buffer which is dired buffer. So I came up with step 3



3) call `aza-kill-other-buffers`. All buffers killed but the current-file.



```elisp
(defun aza-kill-other-buffers ()
  "Kill all buffers but current buffer and special buffers.
(Buffer that start with '*' and white space ignored)"
  (interactive)
  (save-all-buffers-silently)
  (when (y-or-n-p "Really kill all other buffers ? ")
    (let ((killed-bufs 0))
      (dolist (buffer (delq (current-buffer) (buffer-list)))
        (let ((name (buffer-name buffer)))
          (when (and name (not (string-equal name ""))
                     (/= (aref name 0) ?\s)
                     (string-match "^[^\*]" name))
            (cl-incf killed-bufs)
            (funcall 'kill-buffer buffer))))
      (message "Killed %d buffer(s)" killed-bufs))))
```

If you agree, I would like to make PR for this. Lately, I add `  (save-all-buffers-silently)`, I can get rid of it / you can amend it.

Have a great day :)

**Pull request closed without merging**
